<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>MuPDF.NET.Examples.PDF4LLM.Ocr</RootNamespace>
    <AssemblyName>04-Ocr</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MuPDF.NET.PDF4LLM" Version="$(ArtifexMuPDFNetPDF4LLMVersion)" />
    <ProjectReference Include="..\..\Common\Examples.Common.csproj" />
  </ItemGroup>
</Project>
