<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>MuPDF.NET.Examples.MuPDFNet.RewriteImages</RootNamespace>
    <AssemblyName>20-RewriteImages</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="MuPDF.NET" Version="$(ArtifexMuPDFNetVersion)" />
    <ProjectReference Include="..\..\Common\Examples.Common.csproj" />
  </ItemGroup>
</Project>
